### ISSUE TITLE
Unable to SSH into Server after cryptroot unlock via dropbear

### ISSUE THREAD

**Issue by leveled** [TheReal1604/disk-encryption-hetzner#18]
I followed the instructions verbatim from the Ubuntu guide and am running into an issue where after running the cryptroot setup script on dropbear, I am unable to SSH into the server. I am not sure if this is has to do with some hooks in initramfs which prevent further SSH attempts into the box, or if it's a problem with the with the LVM setup itself. There is some ambiguity around the instructions describing the LVM process creation. 

```
We have now to edit your vg0 backup:

blkid /dev/mapper/cryptroot Results in: /dev/mapper/cryptroot: UUID="HEZqC9-zqfG-HTFC-PK1b-Qd2I-YxVa-QJt7xQ"
cp vg0.freespace /etc/lvm/backup/vg0
Now edit the id (UUID from above) and device (/dev/mapper/cryptroot) property in the file according to our installation
```

I wasn't sure exactly where the UUID and device were supposed to go, I put them into the physical volume section of the backup file, but got some warnings later on about sectors not matching. I'm wondering if that's the cause of the issue.

**Comment by TheReal1604** [comment]
Thanks for the issue. @sirtoobii already made a MR which improves this section a lot. Hopefully you found the solution after this long time!
