### ISSUE TITLE
Suggestion: start cryptroot-unlock from dropbear

### ISSUE THREAD

**Issue by ottobaer** [TheReal1604/disk-encryption-hetzner#27]
I don't know if this project is still active. I just did the installation on Debian 10 and it worked great. 

Just an idea, maybe you could add a line to /etc/dropbear-initramfs/config that automatically launches cryptroot-unlock, so the only thing you need to enter in the dropbear ssh is your key: 

#/etc/dropbear-initramfs/config
DROPBEAR_OPTIONS="-c /bin/cryptroot-unlock"

**Comment by TheReal1604** [comment]
Hey @ottobaer ,

this project is still active, but currently mostly driven by contributions. Thanks for your suggestions, I take a look.

**Comment by wnhre2ur8cxx8** [comment]
fixed in #29
