### ISSUE TITLE
thoughts about maintaining this repo ?

### ISSUE THREAD

**Issue by leviwheatcroft** [TheReal1604/disk-encryption-hetzner#5]
It's great to see that this repo is getting some love, we've gone from one guide to 4 in a few months. However, I can see that without some planning we might just end up with an unmaintainable mess. I'd hate to see everyone's hard work in documenting this process become dated and useless, or worse... confusing!

So the question is, is there a way to structure this repo, or the guides, to make things more maintainable?

I note that other contributors have done some work organising the repo, which is a great start.

The problem we have at the moment is that each guide repeats loads of the content of other guides. (you know... don't repeat yourself). That said it's not as easy as making a single merged guide with annotations for different platforms / configurations, because such a thing would make it *more* difficult to maintain and *less* readable.

Maybe a good compromise would be to have a comprehensive "overview" in the front readme, which doesn't include any commands, but explains conceptually what needs to be done at each step. Then the existing guides can have the conceptual wordy stuff removed, and instead just refer to the relevant step from the overview.

Secondly, I think each guide should have certain requirements. For example:

 * frontmatter - mention that there's other guides, mention the overview
 * headings relating to the steps from the overview
 * contrib request - a strong plea to post an issue if a correction is required, and all the info needed when posting such an issue.

**Comment by TheReal1604** [comment]
hi @leviwheatcroft , sounds absolutely legit. Agree that we need a comprehension in the readme and just link to the differences in the distributions.

Unfortunately my time is very limited at the moment, so I can only contribute that for ubuntu (so that it is tested and OK. I take some time over the next weeks to build the first README draft for that and lets take a look together if that matches your thoughts. With the help of the community we can make it even better and for more distributions. :)

Thanks!

**Comment by MaxXor** [comment]
Maybe add a guide for the new cloud servers? Is it basically the same just without configuring the raid?

**Comment by TheReal1604** [comment]
@MaxXor would really like that :) just open a PR

**Comment by Sanafan** [comment]
Just did it on the new EX42-NVME Server. Everything working fine of course without the `dev/sda` and `dev/sdb` command. There i had to enter `dev/nvme0n1` and `dev/nvme1n1`. Thanks a lot for this great description guys!!!

**Comment by TheReal1604** [comment]
@Sanafan thanks for your comment, glad that the howto could help you out. ;)

**Comment by TheReal1604** [comment]
Will close this issue - just fyi: Doesnt work actively on this repo here, but I will merge PRs from time to time. 

Thanks for all the feedback and the PRs. You're great! :heart_eyes:
